// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "RestaurantType": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=Restaurant/design
// --out=$(GOPATH)\src\Restaurant
// --version=v1.3.1

package app
